coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
ignore:
  # ❌ Temporary ignore these items
  - "services/AI-service/app/providers/**"
  - "services/AI-service/app/security/**"