name: Deploy Dagster to Azure Container App

on:
  push:
    branches: 
      - master
    paths:
      - "services/Dagster-scheduler/**"
      - ".github/workflows/deploy-dagster.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure login (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.AZURE_ACR_NAME }}

      - name: Build & push Dagster image
        run: |
          IMAGE=${{ secrets.AZURE_ACR_NAME }}.azurecr.io/dagster:${{ github.sha }}
          docker build -t $IMAGE ./services/Dagster-scheduler
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name ${{ secrets.AZURE_DAGSTER_APP }} \
            --resource-group ${{ secrets.AZURE_RG }} \
            --image $IMAGE

      - name: Show Dagster URL
        run: |
          az containerapp show \
            --name ${{ secrets.AZURE_DAGSTER_APP }} \
            --resource-group ${{ secrets.AZURE_RG }} \
            --query "properties.configuration.ingress.fqdn" -o tsv
